### ISSUE TITLE
Wiring up a backend

### ISSUE THREAD

**Issue by Analect** [apowers313/switchboard#2]
@apowers313 
I had been looking for some Polymer v1.0+ examples ahead of the Polymer Summit in Amsterdam and happened upon your repo. I cloned and did a bower install and ran with a SimpleHTTPServer ... but unlike the publically hosted site (http://switchboard.center/) this doesn't look like it's wired up for a backend. Am I missing some stuff ... would you be able to point me in the right direction.
Thanks very much.
Colum

**Comment by apowers313** [comment]
Hi @Analect - thanks for the note. There is a collection of REST APIs that makes up the backend, but it's all in a private repo right now because its not production ready. In addition, I'm refactoring the APIs right now since my original MVP using Postman couldn't cope with many of the complexities of OAuth.

Big fan of Polymer Summit and happy to help out however I can.

Adam

**Comment by Analect** [comment]
@apowers313 
Adam, sorry for delayed response. I'm going to 'watch' this repo for the solution you end up using, if that's OK. By the way, I just attended the Summit but wasn't in any way involved in the organisation. The various presentations are online here, for your info. : https://www.youtube.com/watch?t=8&v=PxJ2PWwVYbQ ... split out by topic on the right-hand panel.   Rgds, Colum
